### PR TITLE
regex test failure

### PR DESCRIPTION
**Pull request by ericdeansanchez**
Regex test failure; Seems to be a typo. Tests now pass in 2.7 and 3.6.

### CODE REVIEW

**Comment by ericd34n** [comment]
I had worked in some other areas as well, however, those changes were larger than this regex one. I had to wrangle this down to _only_ this regex test failure.

**Comment by ericd34n** [comment]
I was trying to ensure some of the other things I'm doing weren't breaking older python versions, however, I found that running the tests in this conda env that the regex test fails as shown below:

```
Testing started at 9:58 PM ...
/anaconda3/envs/pymodm27/bin/python /Applications/PyCharm.app/Contents/helpers/pycharm/_jb_pytest_runner.py --path /Users/ericd34n/OpenSource/pymodm/test
Launching py.test with arguments /Users/ericd34n/OpenSource/pymodm/test in /Users/ericd34n/OpenSource/pymodm/test

============================= test session starts ==============================
platform darwin -- Python 2.7.14, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
rootdir: /Users/ericd34n/OpenSource/pymodm, inifile:collected 197 items

test_collation.py                                                  [  3%]
test_connection.py .........                                                   [  4%]
test_context_managers.py                                             [  6%]
test_delete_rules.py .............                                           [ 11%]
test_dereference.py ..............                                       [ 18%]
test_errors.py                                                          [ 18%]
test_fields.py .                                       [ 28%]
test_manager.py ...................                                                     [ 30%]
test_model_basic.py ....                                             [ 34%]
test_model_inheritance.py ........                                        [ 38%]
test_options.py .......                                                   [ 41%]
test_queryset.py ......                                [ 53%]
test_related_fields.py ...................................                                       [ 58%]
field_types/test_biginteger_field.py                                   [ 59%]
field_types/test_binary_field.py                                        [ 60%]
field_types/test_boolean_field.py                                       [ 60%]
field_types/test_char_field.py                                         [ 61%]
field_types/test_datetime_field.py                                     [ 62%]
field_types/test_decimal128_field.py                                   [ 63%]
field_types/test_dict_field.py                                        [ 65%]
field_types/test_email_field.py                                        [ 66%]
field_types/test_embedded_document_field.py                      [ 69%]
field_types/test_file_field.py                             [ 76%]
field_types/test_float_field.py                                        [ 77%]
field_types/test_generic_ip_address_field.py                           [ 78%]
field_types/test_geometrycollection_field.py                          [ 80%]
field_types/test_image_field.py                                       [ 81%]
field_types/test_integer_field.py                                      [ 82%]
field_types/test_javascript_field.py                                    [ 83%]
field_types/test_linestring_field.py                                   [ 84%]
field_types/test_list_field.py                                        [ 85%]
field_types/test_multilinestring_field.py                             [ 87%]
field_types/test_multipoint_field.py                                [ 90%]
field_types/test_objectid_field.py                                [ 93%]
field_types/test_point_field.py                                        [ 94%]
field_types/test_polygon_field.py                                      [ 95%]
field_types/test_regular_expression_field.py ...............                          [ 68%]
field_types/test_embedded_document_list_field.py .........................................                                 [ 88%]
field_types/test_multipolygon_field.py ........                                    [ 91%]
field_types/test_ordereddict_field.py .........F
```
Here is the problem:
```
<_sre.SRE_Pattern object at 0x1111acd78> != <_sre.SRE_Pattern object at 0x110c01e40>

Expected :<_sre.SRE_Pattern object at 0x110c01e40>
Actual   :<_sre.SRE_Pattern object at 0x1111acd78>
 <Click to see difference>

self = <test.field_types.test_regular_expression_field.RegularExpressionFieldTestCase testMethod=test_to_python>

    def test_to_python(self):
>       self.assertEqual(self.pattern, self.field.to_python(self.regex))

field_types/test_regular_expression_field.py:31: 

..                                   [ 97%]
field_types/test_url_field.py .....                          [ 96%]
field_types/test_timestamp_field.py                                          [ 98%]
field_types/test_uuid_field.py                                        [100%]

=================================== FAILURES ===================================
________________ RegularExpressionFieldTestCase.test_to_python _________________

self = <test.field_types.test_regular_expression_field.RegularExpressionFieldTestCase testMethod=test_to_python>
```
Other versions of python have no problem with this test. I found the failure to be odd since I was fairly certain you'd automatically be informed about these kinds of failures. It is also a little odd that all tests (except the above) pass with both versions:

This:

```python

def test_to_python(self):
    self.assertEqual(self.pattern, self.field.to_python(self.pattern))

```
And this: 

```
    def test_to_python(self):
>       self.assertEqual(self.pattern, self.field.to_python(self.regex))

field_types/test_regular_expression_field.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test.field_types.test_regular_expression_field.RegularExpressionFieldTestCase testMethod=test_to_python>
first = <_sre.SRE_Pattern object at 0x110c01e40>
second = <_sre.SRE_Pattern object at 0x1111acd78>, msg = None

    def _patched_equals(self, first, second, msg=None):
        try:
            old(self, first, second, msg)
            return
        except AssertionError as native_error:
            if not test_filter or test_filter(self):
                error = EqualsAssertionError(first, second, msg)
                if error.can_be_serialized():
>                   raise error
E                   EqualsAssertionError:  :: <_sre.SRE_Pattern object at 0x110c01e40> != <_sre.SRE_Pattern object at 0x1111acd78>

/Applications/PyCharm.app/Contents/helpers/pycharm/teamcity/diff_tools.py:36: EqualsAssertionError
==================== 1 failed, 196 passed in 14.89 seconds =====================
Process finished with exit code 0
```

Am I missing something here?

**Comment by ShaneHarvey** [comment]
This is indeed a bug. But your fix isn't quite right.  The problem is two-fold:
1. Python regular expression objects  `__eq__` was only recently added to Python 3.6/3.7: https://bugs.python.org/issue28727. Before 3.6, they only compare equal if they are the same exact object (same id).
1. Python caches regular expressions.

```python
Python 2.7.10 (default, Jul 15 2017, 17:16:57)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
>>> import re
>>> p = re.compile('hello', re.UNICODE)
>>> p2 = re.compile('hello', re.UNICODE)
>>> p == p2
True
>>> re.purge()  # Clear the regex object cache
>>> p3 = re.compile('hello', re.UNICODE)
>>> p == p3
False
>>> p
<_sre.SRE_Pattern object at 0x101a18be8>
>>> p2
<_sre.SRE_Pattern object at 0x101a18be8>
>>> p3
<_sre.SRE_Pattern object at 0x101afa418>
>>> p.__eq__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_sre.SRE_Pattern' object has no attribute '__eq__'
>>> p.__cmp__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_sre.SRE_Pattern' object has no attribute '__cmp__'
```

On Python 3.6:
```python
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> p = re.compile('hello', re.UNICODE)
>>> p.__eq__
<method-wrapper '__eq__' of _sre.SRE_Pattern object at 0x104d58440>
>>> re.purge()
>>> p2 = re.compile('hello', re.UNICODE)
>>> p
re.compile('hello')
>>> p2
re.compile('hello')
>>> p == p2
True
>>> p is p2
False
```

So I think the solution is to only compare the flags/pattern when comparing if two regex objects are equal. I.E.:

```python
    def assertRegexObjectsEqual(self, reg1, reg2):
        self.assertEqual(reg1.pattern, reg2.pattern)
        self.assertEqual(reg1.flags, reg2.flags)

    def test_to_python(self):
        self.assertRegexObjectsEqual(
            self.pattern, self.field.to_python(self.regex))
```

**Comment by ericd34n** [comment]
Yeah that passes; I'll have to continue reading up on that. Is there a way we could get this in with a cleaner commit log? Should I make another PR with your improvement so that the commit log only has one commit in it instead of, you know uh, twelve...

**Comment by ShaneHarvey** [comment]
No worries about the commit log. I'll squash and rebase these changes into a single commit before merging.

**Comment by ShaneHarvey** [comment]
Closed in favor of #50.

**Pull request closed without merging**
